spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://100.109.228.49:5432/course
    username: postgres
    password: 123456



spring.flyway:
  validate-migration-naming: true
  url: jdbc:postgresql://100.109.228.49:5432/course
  user: postgres
  password: 123456
  enabled: true
  locations:
    - 'classpath:db/migration'
